### ISSUE TITLE
Edit gallery button don't work in a new gallery

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/pixproof#11]
Daca vrei sa editezi o galerie noua, sa faci drag and drop, nu merge.

![screenshot_4_1024](https://cloud.githubusercontent.com/assets/6790170/8410405/a8d517b6-1e86-11e5-9148-7a54a838c418.png)

Daca dai click pe al doilea tab "Add gallery" si revi pe primul "Edit gallery" atunci totul e ok:

![screenshot_5](https://cloud.githubusercontent.com/assets/6790170/8411057/8dae350e-1e8a-11e5-9a74-878201614a1c.png)

@: https://help.pixelgrade.com/helpdesk/tickets/17575
+1: https://help.pixelgrade.com/helpdesk/tickets/17347

**Comment by vladolaru** [comment]
I've tried to solve this, but this is an issue with the WP core JS and I can't get around it.
