### ISSUE TITLE
Language translation is not working properly

### ISSUE THREAD

**Issue by davidperezgar** [pixelgrade/pixproof#15]
Is not defined 'pixproof' as text domain to load languages. 

Ex.
'name' => __( 'Client Name', 'pixproof_l10n' ),
should be
'name' => __( 'Client Name', 'pixproof' ),

and the language directory is missing.

If you want, I can make a pull request. Which branch?

**Comment by davidperezgar** [comment]
Hello?

**Comment by andreilupu** [comment]
it is done here https://github.com/pixelgrade/pixproof/pull/17
