### ISSUE TITLE
How can i define columns in the plugin?

### ISSUE THREAD

**Issue by davidperezgar** [pixelgrade/pixproof#19]

**Comment by andreilupu** [comment]
You can select the number of columns when you create the gallery in the right panel of the media modal

![screen shot 2015-11-10 at 10 17 36 am](https://cloud.githubusercontent.com/assets/1893980/11057530/7bbcfe16-8794-11e5-9ae2-0513fe7c50d2.png)

**Comment by davidperezgar** [comment]
Thanks, I've used the templates that gives me more versatibilitity...
