### ISSUE TITLE
Warning in WP Dashboard

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/pixproof#29]
> Warning: count(): Parameter must be an array or an object that implements Countable in /app/public/wp-content/plugins/pixproof/features/metaboxes/init.php on line 718

![screenshot at nov 12 12-13-38](https://user-images.githubusercontent.com/6790170/48340897-6632cc00-e674-11e8-902b-57bee6bc1380.png)

**Comment by georgeolaru** [comment]
@vladolaru that seems to show even when wp_debug is not active. 

In case of the Timber theme, it also move down the content a little bit:
![image](https://user-images.githubusercontent.com/1632775/66548568-2d33fd80-eb4a-11e9-9633-2e61c56f7109.png)

**Comment by vladolaru** [comment]
No longer the case as we have rewritten the plugin and the code is back in today's age.
